### ISSUE TITLE
about MADNet

### ISSUE THREAD

**Issue by yuqiangchu** [24wenjie-li/FDIWN#3]
作者您好，请问可以提供下MADNet的测试结果数据集或者是训练好的模型吗，本人有篇论文工作急需与MADNet进行对比，拜托您了~

**Comment by 24wenjie-li** [comment]
链接：https://pan.baidu.com/s/1Ud_j5cikH3uhdahVuvRlAg 
提取码：54am

**Comment by yuqiangchu** [comment]
> 链接：https://pan.baidu.com/s/1Ud_j5cikH3uhdahVuvRlAg 提取码：54am

真的非常非常谢谢您了T T

**Comment by 24wenjie-li** [comment]
不客气

**Comment by chrimy666999** [comment]
> 链接：https://pan.baidu.com/s/1Ud_j5cikH3uhdahVuvRlAg 提取码：54am

作者大佬您好！这个链接失效了，请问还能更新一下吗？万分感谢！祝学术长青~
